### ISSUE TITLE
Unable to login - new install

### ISSUE THREAD

**Issue by joemadd3n** [roblandry/addon-shinobi#5]
# Problem/Motivation

> (Why the issue was filed)
Opened the web UI and tried to login using the super user details from config and received an error
## Expected behavior

> (What you expected to happen)
Expected to be able to login as per the installation instructions
## Actual behavior

> (What actually happened)
Error "Please check your login credentials."
## Steps to reproduce

> (How can someone else make/see it happen)
Not sure, It should be pretty straight-forward
## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Fix it 👍

**Comment by virtuajdub** [comment]
Did you try logging in with the superuser account ?

Check the logs of the "Shinobi Pro" add-on to see if everything went well.
Surf to the superuser admin panel: **http://hassio.local:7440/super or http://127.0.0.1:7440/super**
Log in with the superuser credentials as specified in the add-on configuration.

From there.... you can create user accounts for the normal login page.

**Comment by ghost** [comment]
i habe the same problems. 
getting this errors:
`Shinobi : Web Server Listening on 80
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
This Install of Shinobi is NOT Activated
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2020-12-28T21:51:51+01:00 This Install of Shinobi is NOT Activated  
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
https://licenses.shinobi.video/subscribe
2020-12-28T21:51:52+01:00 Shinobi is ready.  
knexError----------------------------------- START
[Error: select * from `Schedules` - SQLITE_ERROR: no such table: Schedules] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
select * from `Schedules`
knexError----------------------------------- END
Uncaught Exception occured!
TypeError: Cannot read property 'forEach' of undefined
    at /opt/shinobi/libs/scheduler.js:11:18
    at /opt/shinobi/libs/sql.js:186:33
    at cb (util.js:207:31)
    at util.js:191:10
    at hidden (internal/errors.js:291:14)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`
